import type { Metadata } from "next";
import { jetbrainsMono, montserrat, spaceGrotesk, cubano } from './fonts';
import "./globals.css";

export const metadata: Metadata = {
  title: "DeployX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${montserrat.variable} ${spaceGrotesk.variable} ${cubano.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
