import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { jetbrainsMono, montserrat, spaceGrotesk, cubano } from './fonts';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DeployX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} ${montserrat.variable} ${spaceGrotesk.variable} ${cubano.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
